#!/usr/bin/zsh
# zshenv - Alan Morgan

# A bunch more environment variables
export ANACONDA_HOME="$HOME/anaconda3"
export ANDROID_HOME=/opt/android-sdk
export BROWSER=chromium
export CONCARDS_OUTCOME="$HOME/track/concards-data/outcome"
export CONCARDS_PREDICT="$HOME/track/concards-data/predict"
export GOPATH=~/.go
export GPG_TTY=`tty`
export GTK_IM_MODULE=fcitx
export JAVA_HOME=$(/usr/libexec/java_home -v 13 2> /dev/null)
export LC_ALL=en_US.UTF-8
export npm_config_prefix=~/.node_modules
export QEMU_AUDIO_DRV='pa'
export QT_IM_MODULE=fcitx
export TERMINAL="alacritty"
export VISUAL=kak
export EDITOR=$VISUAL
export XDG_CACHE_HOME=$HOME/.cache
export XDG_CONFIG_HOME=$HOME/.config
export PICO_WORK_DIR=$HOME/.lexaloffle/pico-8/carts
export XENVIRONMENT="${HOME}/.Xresources"
export XKB_DEFAULT_LAYOUT=us
export PA_DIR="$HOME/pass"
export XMODIFIERS=@im=fcitx
export PAGER=kak_page
export MANPAGER=kak_man
export RIPGREP_CONFIG_PATH="$HOME/.rgconfig"

# FZF environment variables
BFT="fd -t f --hidden --color=always --ignore-file ~/.dot/search-ignore ."
BFC="fd -t d --hidden --color=always --ignore-file ~/.dot/search-ignore ."
export FZF_DEFAULT_COMMAND="$BFT"
export FZF_DEFAULT_OPTS="--ansi"
export FZF_CTRL_T_COMMAND="($BFT --exact-depth 1; $BFT --exact-depth 2; $BFT --exact-depth 3; $BFT --min-depth 4;) | cat"
export FZF_ALT_C_COMMAND="($BFC --exact-depth 1; $BFC --exact-depth 2; $BFC --exact-depth 3; $BFC --min-depth 4;) | cat"
export TERM='xterm-256color'

# Set the path last, because it depends on an environment variable.
export PATH="$PATH:$HOME/.fzf/bin"
export PATH="$PATH:$HOME/.dot/bin"
export PATH="$PATH:$HOME/.go/bin"
export PATH="$PATH:$HOME/.cargo/bin"
export PATH="$PATH:$HOME/.local/bin"
export PATH="$PATH:$PICO_WORK_DIR/bin"
export PATH="$PATH:$HOME/.pulumi/bin"

# For macs, this will add standard gui apps to the path.
if [ -d /Applications ]; then
    for app_path in /Applications/*; do
        full_path="$app_path/Contents/MacOS"
        if [ -d $full_path ]; then
            export PATH="$PATH:$app_path/Contents/MacOS"
        fi
    done
fi
