#!/bin/zsh
# zshrc - Alan Morgan

# Emacs Mode & History Options
bindkey -e

# Able to edit the line with vim
autoload -z edit-command-line
zle -N edit-command-line
bindkey '^[v' edit-command-line
umask 077 # No permission to group or others.

export PROMPT='%F{yellow}>%f '
export CLICOLOR=1

# History & prompt
export HISTFILE=~/.zhistory
export SAVEHIST=100000
export HISTSIZE=100000

# Set some history options
setopt APPEND_HISTORY       # Addition of the history file
setopt HIST_IGNORE_ALL_DUPS # Ignore all repetitions of commands
setopt HIST_FIND_NO_DUPS    # Do not display the string found earlier
setopt HIST_IGNORE_DUPS     # Ignore rows if they are duplicates
setopt HIST_REDUCE_BLANKS   # Delete empty lines from history file
setopt HIST_IGNORE_SPACE    # Ignore a record starting with a space
setopt EXTENDED_HISTORY     # Add additional data to history like timestamp
setopt INC_APPEND_HISTORY   # Add immediately
setopt SHARE_HISTORY        # Share history between session/terminals
setopt interactivecomments  # Allow comments in interactive mode.
setopt +o nomatch

source_file() {
    if [ -f "$1" ]; then source "$1" 2> /dev/null; fi
}

source_file "$HOME/.local_aliases"
source_file "$HOME/.aliases"
source_file "$HOME/.dot/local_zshrc"
source_file "$HOME/.dot/zbindings"

# bun completions
[ -s "/home/alan/.bun/_bun" ] && source "/home/alan/.bun/_bun"
[ -s "/home/alan/.sympldot/init" ] && source "/home/alan/.sympldot/init"
