#!/bin/bash
# alias
alias a='alias'

# maven
liquibase() { mvn -DskipTests=true -Drelease.environment=local -Dserver=$1 -Ddatabase=$2 -Dusername=liquibase -Dpassword=l1qu1b\$e -Dcontexts=$3 clean install }
a mvnc='mvn clean'
a mvnv='mvn verify -DskipDependencyCheck=true'
a mvnp='mvn package -DskipDependencyCheck=true -DskipTests=true'
a mvni='mvn install -DskipDependencyCheck=true -DskipTests=true'
a mvnt='mvn com.clearwateranalytics:dependency:resolve-transitives'
a mvnj="mvn javadoc:javadoc"
mvntc() { mvn test -DfailIfNoTests=false -Dtest=$(filebasename $1) }

filebasename() { basename $1 | cut -f 1 -d '.' }

# update files
a ua='unalias -a; source ~/.aliases'
a uz='unalias -a; source ~/.zshenv; source ~/.zshrc'

# mount
a mone="sudo mount /dev/sda1 /mnt"
a mountmicrosd=mountcard
a mountsdcard=mountcard
a mtwo="sudo mount /dev/sdb1 /mnt2"
a umnt='sudo umount /mnt'
a umone="sudo umount /mnt"
a umtwo="sudo umount /mnt2"

# git
a repos='cd ~/repos'
a rep=repos
a cg='cd $(git rev-parse --show-toplevel)'
a gs='git status'
a gst='git stash'
a g='git'
a gu='git pull'
a gf='git fetch'
a ga='git add'
a gaa='git add --all'
a gr='git rebase'
a gra='git rebase --abort'
a grc='git rebase --continue'
a gc='git add --all; git commit;'
a gca='git add --all; git commit --amend;'
a gcl='git clone'
a gm='git merge'
a gmf='git merge --ff-only'
a gp='git push'
a gpf='git push --force'
a gpn='git push -u origin $(git branch --show-current)'
a gpd='git push origin --delete $(git branch --show-current)'
a gd='git diff HEAD'
a gdf='git diff --name-only HEAD'
a gl='git log'
a glo="gl --pretty='%h %ad %an: %s%d' --date=short"
a gla="glo --all --graph"
a glf="gl --name-status --find-renames --oneline"
a gt='git tag'
a gb='git branch'
a gba='git branch --all'
a gpa='git push --all origin'
a gbc='git branch --show-current'
a gk='git checkout'
a gk-='git checkout -'
a gkb='git checkout -b'
a gkt='git checkout --track'
a gbl='git blame'
a gwl='git worktree list'
gwa() { git worktree add "$HOME/work/$1" }
gwr() { git worktree remove --force "$HOME/work/$1" }
a gitsvnignore='git svn show-ignore >> .git/info/exclude'


# git list cases
# First parameter is where you are merging into.
# Second parameter is your feature branch. Optional if you are already checked out there.
glc() {
    git log $1..$2 --oneline | grep -io1 '\([A-Za-z]\+-\d\+\)' | sort -u | sed ':a; N; $!ba; s/\n/, /g'
}

# github
a ghi='gh issue'
a ghil='gh issue list'

# mpsyt & youtube-dl
a mpsyt='rm ~/.config/mps-youtube/cache* 2> /dev/null; mpsyt'
a chiptune='mpv http://79.120.11.40:8000/chiptune.ogg'

a getvid="youtube-dl -f 18"
a vid2mp3='youtube-dl --extract-audio --audio-format mp3'

# golang
a gocover='go test -coverprofile=/tmp/cover.out; go tool cover -html=/tmp/cover.out'

# vim & kak
a vor='kak ~/sync/library/dicts/esperanto_dictionary.txt'
a vim='nvim'
a vi='nvim'
a v='nvim'
a k="kak"
a editsnips="kak ~/.dotfiles/snips/*"
a es='editsnips'
a ev='kak ~/.config/nvim/lua/init.lua'
a ek='kak ~/.config/kak/kakrc'
a ea='kak ~/.aliases'
a ez='kak ~/.zshrc ~/.zshenv'

# diary
a diary='cd ~/diary/alan'
a di='diary'
a jrn='kak ~/diary/alan/{2021_diary,motive,achievements,todos,plans,timelog}.md'
a rnj='jrn'
a nrj='jrn'
a njr='jrn'
a tl='jrn'
a rjn='jrn'
a jnr='jrn'
a ap='achieve_parser ~/diary/alan/timelog.md'

# acpi
a acip=acpi
a piac=acpi
a paci=acpi
a ipca=acpi
a ipac=acpi
a paic=acpi
a pcai=acpi
a pcia=acpi
a pica=acpi
a aicp=acpi
a aipc=acpi
a apci=acpi
a apic=acpi
a iacp=acpi
a cpai=acpi
a cpia=acpi
a cpi=acpi
a ciap=acpi
a cipa=acpi
a caip=acpi
a capi=acpi
a iapc=acpi
a icap=acpi
a icpa=acpi
a acp=acpi
a ac=acpi

# docker
did() { docker ps | grep "$1" | cut -d ' ' -f1 }
dl() { docker logs $(did $1) }
a dkl='docker kill $(docker ps | awk "{print \$1;}" | tail -n 1)'
a dps='docker ps'
a db.='docker build .'

# gui
a i3l='i3lock -c 000000'
a 3il='i3l'
a sx=startx

# sdcv
a define=sdcv
a defin=sdcv
a defi=sdcv
a def=sdcv
a dic=sdcv
a dictionary=sdcv
a dict=sdcv

# cd
a dot='cd ~/.dotfiles'
a sdcard='cd /sdcard; ls;'
a down='cd ~/Downloads; ls'
a drop='cd ~/Dropbox; ls'
a cdpico="cd ~/.lexaloffle/pico-8/carts"
a cv="cd ~/.config/nvim"
a c='cd'
a c-='cd -'
a c~='cd;cd' # Example: `c~ .dotfiles` will open '~/.dotfiles'.
a c.='cd ..'
a sand='cd ~/repos/sand'

# dropbox
a rapiddrop="while [ true ]; do clear; dropstat; sleep 1; done"
a redrop='pkill dropbox; echo dropbox | bash - &'
a dropfile="dropbox-cli sharelink"
a dropls='dropbox-cli ls'
a dropstat='dropbox-cli status'

# clear
a cl=clear

# xclip
a copycurrent='echo cd $(pwd) | xclip'
a copypath=copycurrent

# make
a ake=make
a maake=make
a kmake=make
a jake=make
a jmake=make
a maek=make
a mak=make
a mkae=make
a mkea=make
a amke=make

# exit
a xeit='exit'
a quit='exit'
a eitx='exit'
a eixt='exit'
a etix='exit'
a etxi='exit'
a exti='exit'
a xite='exit'
a xit='exit'
a ext='exit'
a xti='exit'

# sbri
sbri() { echo $(expr $1 \* 192) > /sys/class/backlight/intel_backlight/brightness }
a supbri="sbri 100"
a mid="sbri 50"
a dim="sbri 20"
a bri="sbri 80"
a morbri="sbri 90"
a mordim="sbri 10"
a supdim="sbri 1"

# localectl & setxkbmap
a cdv='localectl set-keymap --no-convert dvorak'
a cqw='localectl set-keymap --no-convert us'
a gdv='setxkbmap -layout "us" -variant "dvorak"'
a gqw='setxkbmap -layout "us"'

# ls
a ls='exa'
a l='ls'
a lst='exa --tree'
a lt='lst'
a lls='ls'
a lss='ls'
a sl='ls'
a la='ls -a'
a lsa='ls -a'
a ll='ls -l'
a l.='ls -d .*'
a lsla='ls -la'
a lla='ls -la'
a lsl='ls -l'
a sls='ls -l'
a ssl='ls -l'
a ls..="ls .."

# poweroff
a poweraff='poweroff'
a pwoeroff='poweroff'
a pworeoff='poweroff'
a powreoff='poweroff'
a oweroff='poweroff'

# w3m
a w3m='w3m -no-mouse'
a ddg='w3m ddg.gg'

# xrandr
a tolap="xrandr --output HDMI-1 --off --output eDP-1 --auto --mode 1366x768 --panning 1366x768"
a tomirror="xrandr --output HDMI-1 --mode 1366x768 --output eDP-1 --same-as HDMI-1"

# feh
a feh='feh --force-aliasing --scale-down'
a rndbkgd="feh --randomize --bg-fill ~/Pictures/photos/*"
a difbkgd="rndbkgd"

# zathura
a zath=zathura

# systemctl
a renet='systemctl restart NetworkManager.service'
a printer='systemctl start org.cups.cupsd'
a nonet='systemctl stop NetworkManager.service'
a netman='systemctl start NetworkManager.service'
a noprinter='systemctl stop org.cups.cupsd'

# pico8
a p8tool='~/repos/picotool/p8tool'
a pico="pico8"

# rm
a rmrf="rm -rf"
a rmr="rm -r"
a rd="rmdir"

# pass
a pe='pass edit'

# PS1
a tops='PS1="[\u-\[\033[0;31m\]\#\[\033[0m\] \W]\$ "'
a nops='PS1="$ "'

# synclient
a mouse='synclient TouchpadOff=0'
a nomouse='synclient TouchpadOff=1'

# sudo
a psudo='sudo env "PATH=$PATH" '
a sudo='sudo '

# publish
a listchinesefonts='fc-list :lang=zh'
a markdowntopdf='pandoc --pdf-engine=xelatex -V CJKmainfont="Source Han Sans CN" -o' # outputfile then input file.
viewmarkdown() { md2html $1 | qutepipe }
a vm='viewmarkdown'

# concards
a cards="cd ~/diary/alan/cards"
a ca="cards"
a cnc="concards ~/diary/alan"

# list things for fzf
_fzf_compgen_path() { fd -t f -t d . "$1" }
a fzf='fzf --height 40% --reverse'
a kbf_git_branch="git branch -a | sed 's/^ *//g' | grep -v '*'"
a kbf_ssh_hosts="sed -rn 's/^\s*Host\s+(.*)$/\1/ip' ~/.ssh/config ~/.ssh/local_ssh 2> /dev/null | xargs -n1"

# Thank you: https://gist.github.com/igemnace/9b6fb8c2885c3e35299b3a122e1009e5
a fzf_apropos='apropos "." 2> /dev/null | cut -f 1 -d "(" | uniq | fzf'

# Pomodoro. Countdown is a golang program.
a pm='countdown 25m && echo times up, next task | espeak; countdown 15m && echo times up, next task | espeak'

# clipboard
a ccl=cclip
a pcl=pclip

# xargs
a xargs='xargs '
a x='xargs '

# TODO: Make an fzf for the screen with this script:
# bind-key P 'capture-pane' \; capture-pane -S - \; save-buffer /tmp/tmux \; delete-buffer
#

# Ripgrep replace.
rr() { rg "$1" "${@:3}" -l | xargs sed -Ei "s^$1^$2^g" }
rmv() { mv $1 "$(dirname $1)/$2" } # Mv a file local to its directory.
rcp() { cp $1 "$(dirname $1)/$2" } # Cp a file local to its directory.

# My hacky way to make a video 2x speed.
# vidspeed <input-file> <output-file>
doublespeed() {
    mencoder -speed 2 -o ".tmp-$2" -oac pcm -ovc lavc "$1"
    ffmpeg -vn -i ".tmp-$2" ".tmp-old-$2.wav"
    sox ".tmp-old-$2.wav" ".tmp-$2.wav" pitch -1200
    mencoder -ovc copy -oac copy -audiofile ".tmp-$2.wav" ".tmp-$2" -o "$2"
    rm ".tmp-old-$2.wav" ".tmp-$2" ".tmp-$2.wav"
}

# random
ssht() { ssh $1 -t tmux "${@:2}" }
a pomo='while true; do echo "WORK TIME"; sleep 25m; speak "timez up... break time" > /dev/null 2>&1; echo "BREAK TIME"; sleep 5m; speak "timez up... start working again" > /dev/null 2>&1; done'
a u='echo -e "$(whoami)@$(hostname)"'
a bn='basename'
a p='pwd'
a wai=whoami
a rgl='rg -l'
a lam='lookatme --live -e terminal'
a pipi='pip install --user'
a bc='bc -q'
a dd='dd status=progress'
a du='du -h'
a df='df -h'
a emacs='emacs -nw'
a fb="~/repos/fuzzybird/fuzzybird.py --hashtag"
a int='sudo wifi-menu'
a lid="echo locked > '/tmp/.lid-lock-file'"
a lock="physlock"
a pavucontrol="ncpamixer"
a pinger='ping www.google.com'
a renginx="sudo nginx -s reload"
a r='ranger'
a ta='tmux attach'
a updatexterm='xrdb merge ~/.Xresources'
a watch='watch -c -d'
a daet='date'
a slblk='lsblk'
