#!/bin/bash
# alias
alias a='alias'

# maven
a mvnci='mvn clean install'
a mvncc='mvn clean compile'
a mvncid='mvnci -DskipDependencyCheck=true'
a mvncidt='mvnci -DskipDependencyCheck=true -DskipTests=true'
a mvntr='mvn com.clearwateranalytics:dependency:resolve-transitives'
a mvnj="mvn javadoc:javadoc"
a mvnp="mvn package"

# source
a testbash='source $(cat > /tmp/.testbash; echo /tmp/.testbash)';
a updatealias='source ~/.aliases'
a updatebash='source ~/.bashrc'
a updateprofile='source ~/.profile'
a ua='updatealias'
a ub='updatebash'
a up='updateprofile'
a uz='source ~/.zshenv; source ~/.zshrc'

# mount
a mone="sudo mount /dev/sda1 /mnt"
a mountmicrosd=mountcard
a mountsdcard=mountcard
a mtwo="sudo mount /dev/sdb1 /mnt2"
a umnt='sudo umount /mnt'
a umone="sudo umount /mnt"
a umtwo="sudo umount /mnt2"

# git
a repos='cd ~/repos'
a rep=repos
a cg='cd $(git rev-parse --show-toplevel)'
a gs='git status'
a gst='git stash'
a g='git'
a gu='git pull'
a gf='git fetch'
a ga='git add'
a gaa='git add --all'
a gr='git rebase'
a gc='git add --all; git commit;'
a gcl='git clone'
a gm='git merge'
a gmf='git merge --ff-only'
a gp='git push'
a gpf='git push --force'
a gpn='git push -u origin $(git branch --show-current)'
a gpd='git push origin --delete $(git branch --show-current)'
a gd='git diff HEAD'
a gdf='git diff --name-only HEAD'
a gl='git log'
a glo="gl --pretty='%h %ad %an: %s%d' --date=short"
a gla="glo --all --graph"
a glf="gl --name-status --find-renames --oneline"
a gt='git tag'
a gb='git branch'
a gba='git branch --all'
a gpa='git push --all origin'
a gbc='git branch --show-current'
a gk='git checkout'
a gkb='git checkout -b'
a gkt='git checkout --track'
a gbl='git blame'
a gitsvnignore='git svn show-ignore >> .git/info/exclude'

# mpsyt & youtube-dl
a mpsyt='rm ~/.config/mps-youtube/cache* 2> /dev/null; mpsyt'
a chiptune='mpsyt "set player cvlc", "set playerargs --no-video", "play chiptune"'
a getvid="youtube-dl -f 18"
a vid2mp3='youtube-dl --extract-audio --audio-format mp3'

# golang
a gocover='go test -coverprofile=/tmp/cover.out; go tool cover -html=/tmp/cover.out'

# vim & kak
a vim='nvim'
a vi='nvim'
a v='nvim'
a k="kak"
a editsnips="kak ~/.dotfiles/snips/*"
a es='editsnips'
a ev='kak ~/.config/nvim/lua/init.lua'
a ek='kak ~/.config/kak/kakrc'
a ea='kak ~/.aliases'
a ez='kak ~/.zshrc ~/.zshenv'

# diary
a diary='cd ~/diary/alan'
a di='diary'
a jrn='kak ~/diary/alan/{2021_diary,timelog,achievements,plans,todos}.md'
a rnj='jrn'
a nrj='jrn'
a njr='jrn'
a tl='jrn'
a rjn='jrn'
a jnr='jrn'
a ap='achieve_parser ~/diary/alan/timelog.md'

# acpi
a acip=acpi
a piac=acpi
a paci=acpi
a ipca=acpi
a ipac=acpi
a paic=acpi
a pcai=acpi
a pcia=acpi
a pica=acpi
a aicp=acpi
a aipc=acpi
a apci=acpi
a apic=acpi
a iacp=acpi
a cpai=acpi
a cpia=acpi
a cpi=acpi
a ciap=acpi
a cipa=acpi
a caip=acpi
a capi=acpi
a iapc=acpi
a icap=acpi
a icpa=acpi
a acp=acpi
a ac=acpi

# i3
a 3il='i3l'
a iomut=imout
a meout=imout
a i3l='i3lock -c 000000'
a ruin=runi
a rnui=runi
a runi=startx

# sdcv
a define=sdcv
a defin=sdcv
a defi=sdcv
a def=sdcv
a dic=sdcv
a dictionary=sdcv
a dict=sdcv

# cd
a dot='cd ~/.dotfiles'
a sdcard='cd /sdcard; ls;'
a down='cd ~/Downloads; ls'
a drop='cd ~/Dropbox; ls'
a cdpico="cd ~/.lexaloffle/pico-8/carts"
a cv="cd ~/.config/nvim"
a c='cd'
a c-='cd -'
a c~='cd;cd' # Example: `c~ .dotfiles` will open '~/.dotfiles'.
a c.='cd ..'
a sand='cd ~/repos/sand'

# dropbox
a rapiddrop="while [ true ]; do clear; dropstat; sleep 1; done"
a redrop='pkill dropbox; echo dropbox | bash - &'
a dropfile="dropbox-cli sharelink"
a dropls='dropbox-cli ls'
a dropstat='dropbox-cli status'

# clear
a cls=clear
a clera=clear

# xclip
a copycurrent='echo cd $(pwd) | xclip'
a copypath=copycurrent

# make
a ake=make
a maake=make
a kmake=make
a jake=make
a jmake=make
a maek=make
a mak=make
a mkae=make
a mkea=make
a amke=make

# exit
a xeit='exit'
a quit='exit'
a eitx='exit'
a eixt='exit'
a etix='exit'
a etxi='exit'
a exti='exit'
a xite='exit'
a xit='exit'
a ext='exit'
a xti='exit'

# sbri
a supbri="sbri 100"
a mid="sbri 50"
a dim="sbri 20"
a bri="sbri 80"
a morbri="sbri 90"
a mordim="sbri 10"
a supdim="sbri 1"

# localectl & setxkbmap
a cdv='localectl set-keymap --no-convert dvorak-programmer'
a cqw='localectl set-keymap --no-convert us'
a gdv='setxkbmap -layout "us" -variant "dvorak"'
a gqw='setxkbmap -layout "us"'
a gwm='setxkbmap -layout "us" -variant "workman"'

# ls
a ls='exa'
a l='ls'
a lst='exa --tree'
a lt='lst'
a lls='ls'
a lss='ls'
a sl='ls'
a la='ls -A'
a lsa='ls -A'
a ll='ls -l'
a l.='ls -d .*'
a lsla='ls -la'
a lla='ls -la'
a lsl='ls -l'
a sls='ls -l'
a ssl='ls -l'
a ls..="ls .."

# poweroff
a poweraff='poweroff'
a pwoeroff='poweroff'
a pworeoff='poweroff'
a powreoff='poweroff'
a oweroff='poweroff'

# w3m
a w3m='w3m -no-mouse'
a googleit='w3m www.google.com'

# xrandr
a tolap="xrandr --output HDMI-1 --off --output eDP-1 --auto --mode 1366x768 --panning 1366x768"
a tomirror="xrandr --output HDMI-1 --mode 1366x768 --output eDP-1 --same-as HDMI-1"

# feh
a feh='feh --force-aliasing --scale-down'
a rndbkgd="feh --randomize --bg-fill ~/Pictures/photos/*"
a difbkgd="rndbkgd"

# zathura
a zath=zathura

# systemctl
a renet='systemctl restart NetworkManager.service'
a printer='systemctl start org.cups.cupsd'
a nonet='systemctl stop NetworkManager.service'
a netman='systemctl start NetworkManager.service'
a noprinter='systemctl stop org.cups.cupsd'

# pico8
a p8tool='~/repos/picotool/p8tool'
a pico="pico8"

# rm
a rmrf="rm -rf"
a rmr="rm -r"

# pass
a pe='pass edit'

# PS1
a tops='PS1="[\u-\[\033[0;31m\]\#\[\033[0m\] \W]\$ "'
a nops='PS1="$ "'

# synclient
a mouse='synclient TouchpadOff=0'
a nomouse='synclient TouchpadOff=1'

# sudo
a psudo='sudo env "PATH=$PATH" '
a sudo='sudo '

# publish
a listchinesefonts='fc-list :lang=zh'
a markdowntopdf='pandoc --pdf-engine=xelatex -V CJKmainfont="Source Han Sans CN" -o' # outputfile then input file.
viewmarkdown() { md2html $1 | qutepipe }
a vm='viewmarkdown'

# concards
a cards="cd ~/diary/alan/cards"
a ca="cards"
a cnc="concards ~/diary/alan"

# list things for fzf
a fzf='fzf --height 40% --reverse'
a kbf_git_branch="git branch -a | sed 's/^ *//g' | grep -v '*'"
a kbf_ssh_hosts="sed -rn 's/^\s*Host\s+(.*)$/\1/ip' ~/.ssh/config ~/.ssh/local_ssh 2> /dev/null | xargs -n1"

# Thank you: https://gist.github.com/igemnace/9b6fb8c2885c3e35299b3a122e1009e5
a fzf_apropos='apropos "." 2> /dev/null | cut -f 1 -d "(" | uniq | fzf'

# Pomodoro. Countdown is a golang program.
a pm='countdown 25m && echo times up, next task | espeak; countdown 15m && echo times up, next task | espeak'

# random
a lam='lookatme --live -e terminal'
a vo='i3b_volume'
a pipi='pip install --user'
a bc='bc -q'
a dd='dd status=progress'
a du='du -h'
a df='df -h'
a emacs='emacs -nw'
a fb="~/repos/fuzzybird/fuzzybird.py --hashtag"
a int='sudo wifi-menu'
a lid="echo locked > '/tmp/.lid-lock-file'"
a lock="physlock"
a pavucontrol="ncpamixer"
a pinger='ping www.google.com'
a renginx="sudo nginx -s reload"
a r='ranger'
a ta='tmux attach'
a updatexterm='xrdb merge ~/.Xresources'
a watch='watch -c -d'
a daet='date'
a slblk='lsblk'
