#!/bin/bash
# Alan's basic Arch Linux install script.
# This has all the things that I normally use on an arch box.
# You probably want to run this script as root.

echo "Installing packages..."
pacman -Syy
pacman --noconfirm -S sudo zsh neovim python-neovim glibc ripgrep tmux

echo "Creating user (you need to enter a password)..."
useradd -m -G wheel -s /bin/zsh alanxoc3
passwd alanxoc3

echo "User configuration..."
sudo -i -u alanxoc3 << EOF
# Download dotfiles
git clone https://github.com/alanxoc3/dotfiles.git ~/.dotfiles

# Get dotfile stuff.
pushd ~/.dotfiles
echo '[user]
   email = ***REMOVED***
   name = Alan Morgan' > local_gitconfig

./setup.sh
popd

# Vim Plug
sh -c 'curl -fLo "${XDG_DATA_HOME:-$HOME/.local/share}"/nvim/site/autoload/plug.vim --create-dirs https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim'

# Zsh
chsh -s /bin/zsh

EOF
