#!/bin/bash
# Alan's arch install script for the user.
# This must be run after the root install, as the non-root user.

echo "Downloading dotfiles..."
git clone https://github.com/alanxoc3/dotfiles.git ~/.dotfiles

# Get dotfile stuff.
pushd ~/.dotfiles
echo '[user]
   email = ***REMOVED***
   name = Alan Morgan' > local_gitconfig

./setup.sh
popd

# Vim Plug
sh -c 'curl -fLo "${XDG_DATA_HOME:-$HOME/.local/share}"/nvim/site/autoload/plug.vim --create-dirs https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim'

mkdir repos
pushd repos
popd

# How to install a minecraft server.
# git clone https://aur.archlinux.org/minecraft-server.git
# pushd minecraft-server
# makepkg -si --noconfirm
# popd
#
