# ~/.config/himalaya/config.toml

name = "Alan Morgan"
downloads-dir = "/home/alanxoc3/Downloads/"
signature-delimiter = "-- "
signature = "Alan Morgan"

[xoc3]
default = true
email = "alan@xoc3.io"

# Used for receiving email.
imap-host = "xoc3.io"
imap-port = 993
imap-login = "alan"
imap-passwd-cmd = "pass show _servers/linode"

# Used for sending email.
smtp-host = "xoc3.io"
smtp-port = 587
smtp-starttls = true
smtp-login = "alan"
smtp-passwd-cmd = "pass show _servers/linode"

[gmail]
email = "alanxoc3@gmail.com"

imap-host = "imap.gmail.com"
imap-port = 993
imap-login = "alanxoc3@gmail.com"
imap-passwd-cmd = "pass show gmail"

smtp-host = "smtp.gmail.com"
smtp-port = 465
smtp-login = "alanxoc3@gmail.com"
smtp-passwd-cmd = "pass show gmail"
