#!/bin/bash
# Alan's basic Arch Linux install script.
# This has all the things that I normally use on an arch box.
# You probably want to run this script as root.

pacman -Syy
pacman --noconfirm -S zsh neovim python-neovim glibc ripgrep

# Vim plug
sh -c 'curl -fLo "${XDG_DATA_HOME:-$HOME/.local/share}"/nvim/site/autoload/plug.vim --create-dirs \
      https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim'

# Use zsh
chsh -s /bin/zsh
