#!/bin/sh
# create modes, can't be parallelized
riverctl declare-mode passthrough
riverctl declare-mode record

# easy way to switch between color theme
# no parallel, because it's cleaner that way
NORMAL_MODE_COLOR='     riverctl background-color 0x111D35; riverctl border-color-focused 0x065AB5; riverctl border-color-unfocused 0x1d2b53; riverctl border-color-urgent 0x1d2b53'
RECORD_MODE_COLOR='     riverctl background-color 0x291814; riverctl border-color-focused 0xBE1250; riverctl border-color-unfocused 0x422136; riverctl border-color-urgent 0x422136'
PASSTHROUGH_MODE_COLOR='riverctl background-color 0x000000; riverctl border-color-focused 0xC2C3C7; riverctl border-color-unfocused 0x5F574F; riverctl border-color-urgent 0x5F574F'
eval "$NORMAL_MODE_COLOR"

# order of this command block is important
# before starting other wayland services i use through systemd, i need to have important env variables imported into systemd
# and finally start up the other services
riverctl default-layout rivertile
systemctl import-environment --user DISPLAY WAYLAND_DISPLAY
systemctl restart --user gammastep rivertile foot-server &

# start with styling and general configuration
riverctl set-repeat 50 300 &
riverctl border-width 8 &

# general mouse configuration
riverctl input 2362:628:PIXA3854:00_093A:0274_Touchpad tap enabled &
riverctl input 2362:628:PIXA3854:00_093A:0274_Touchpad click-method clickfinger &
riverctl input 2362:628:PIXA3854:00_093A:0274_Touchpad disable-while-typing disabled &

# float exception for alacritty when opened in special way (homespun dmenu with fzf)
riverctl float-filter-add app-id progterm &

for mode in normal record; do
    riverctl map $mode Super         N send-to-output next

    # configuration related to alacritty setup
    riverctl map $mode Super         Space  spawn 'alacritty --class progterm -e /bin/zsh -li -c '\''export FZF_DEFAULT_OPTS="--height 100% --reverse"; fzf_gui_modes'\' &
    riverctl map $mode Super         Return spawn 'alacritty -e /bin/zsh -li -c tmux' &
    riverctl map $mode Super+Shift   Return spawn 'alacritty -e /bin/zsh -li -c "tmux attach"' &
    riverctl map $mode Super+Control Return spawn 'alacritty -e /bin/zsh -li' &

    # view navigation
    riverctl map $mode Super H focus-view previous &
    riverctl map $mode Super J focus-view next &
    riverctl map $mode Super L focus-view next &
    riverctl map $mode Super K focus-view previous &

    riverctl map $mode Super+Shift H swap       previous &
    riverctl map $mode Super+Shift J swap       next &
    riverctl map $mode Super+Shift K swap       previous &
    riverctl map $mode Super+Shift L swap       next &

    riverctl map $mode Super+Control H send-layout-cmd rivertile "main-location left" &
    riverctl map $mode Super+Control J send-layout-cmd rivertile "main-location bottom" &
    riverctl map $mode Super+Control K send-layout-cmd rivertile "main-location top" &
    riverctl map $mode Super+Control L send-layout-cmd rivertile "main-location right" &

    # state change
    riverctl map $mode Super Q close &
    riverctl map $mode Super T toggle-float &
    riverctl map $mode Super F toggle-fullscreen &
    riverctl map $mode Super+Shift Escape exit &
    riverctl map $mode Super Escape spawn 'waylock --init-color 0x000000 --input-color 0x1d2b53 --fail-color 0xff004d' &

    # screenshot
    riverctl map $mode None Print spawn 'sh -c '\''grim -g "$(slurp)" - | wl-copy'\' &

    # change main size
    riverctl map $mode Super Bracketleft  send-layout-cmd rivertile "main-ratio -0.05" &
    riverctl map $mode Super Bracketright send-layout-cmd rivertile "main-ratio +0.05" &

    # moving floating windows
    riverctl map-pointer $mode Super BTN_LEFT  move-view &
    riverctl map-pointer $mode Super BTN_RIGHT resize-view &

    # switching workspaces/tags
    for i in $(seq 1 3); do
        tags=$((1 << ($i - 1)))
        riverctl map $mode Super $i set-focused-tags $tags &
        riverctl map $mode Super+Shift $i set-view-tags $tags &
        riverctl map $mode Super+Control $i toggle-focused-tags $tags &
        riverctl map $mode Super+Shift+Control $i toggle-view-tags $tags &
    done
done

# available for normal, record, and locked modes
for mode in normal record locked; do
    riverctl map $mode None XF86AudioPlay         spawn 'systemctl --user is-active radico8-player && systemctl --user stop radico8-player || systemctl --user start radico8-player' &
    riverctl map $mode None XF86AudioRaiseVolume  spawn 'pamixer -i 5'&
    riverctl map $mode None XF86AudioLowerVolume  spawn 'pamixer -d 5' &
    riverctl map $mode None XF86AudioMute         spawn 'pamixer --toggle-mute' &
    riverctl map $mode None XF86MonBrightnessUp   spawn 'light -A 10' &
    riverctl map $mode None XF86MonBrightnessDown spawn 'light -U 10' &
done

# passthrough mode doesn't allow any keybindings besides super+shift+f11
riverctl map normal      Super       F11 spawn "riverctl enter-mode passthrough; $PASSTHROUGH_MODE_COLOR" &
riverctl map passthrough Super+Shift F11 spawn "riverctl enter-mode normal;      $NORMAL_MODE_COLOR" &
