#!/bin/bash

# Thanks to: https://stackoverflow.com/questions/59895/how-to-get-the-source-directory-of-a-bash-script-from-within-the-script-itself
SCRIPT_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null 2>&1 && pwd )"

# cf actual_file link_file
cf() {
  SRC="$SCRIPT_DIR/$1"
  DST="$HOME/$2"
  if [[ $1 =~ ^/ ]]; then SRC=$1; fi
  if [[ $2 =~ ^/ ]]; then DST=$2; fi

  if [ -e "$SRC" ]; then
    rm -f "$DST"
    mkdir -p "$(dirname "$DST")"
    ln -s "$SRC" "$DST"
  fi
}

cfp() {
  SRC="$SCRIPT_DIR/$1"
  DST="$HOME/$2"
  if [[ $1 =~ ^/ ]]; then SRC=$1; fi
  if [[ $2 =~ ^/ ]]; then DST=$2; fi

  if [ -e "$SRC" ]; then
    rm -f "$DST"
    mkdir -p "$(dirname "$DST")"
    cp -f "$SRC" "$DST"
    chmod 755 "$DST"
  fi
}

if [ "${EUID:-$(id -u)}" -eq 0 ]; then # run as root

cfp sys/start-river-alan            /usr/local/bin/start-river-alan
cfp sys/greetd.toml                 /etc/greetd/config.toml
cfp sys/radico8-player.service      /etc/systemd/user/radico8-player.service
cfp sys/foot-server.service         /etc/systemd/user/foot-server.service
cfp sys/wl-gammarelay-rs.service    /etc/systemd/user/wl-gammarelay-rs.service
cfp sys/rivertile.service           /etc/systemd/user/rivertile.service
cfp sys/foot-server.service         /etc/systemd/user/foot-server.service
cfp sys/keyd.conf                   /etc/keyd/default.conf
cfp sys/pipewire-input-denoise.conf /etc/pipewire/pipewire.conf.d/99-input-denoising.conf
cfp sys/shells                      /etc/shells

systemctl daemon-reload

else # run as user

cf usr/zshrc              .zshrc
cf usr/zshenv             .zshenv
cf usr/aliases            .aliases
cf usr/tmuxconf           .tmux.conf
cf usr/local_aliases      .local_aliases
cf usr/local_gitconfig    .local_gitconfig
cf usr/gitignore          .gitignore
cf usr/git-templates      .git-templates
cf usr/kak                .config/kak
cf usr/kak-lsp            .config/kak-lsp
cf usr/mpv.conf           .config/mpv/mpv.conf
cf usr/gitconfig          .config/git/config
cf usr/riverconfig        .config/river/init
cf usr/foot.ini           .config/foot/foot.ini
cf usr/ssh-config         .ssh/config
cf usr/mimeapps.list      .config/mimeapps.list
cf usr/alacritty.yml      .config/alacritty/alacritty.yml
cf usr/search-ignore      .config/fd/ignore
cf usr/himalaya.toml      .config/himalaya/config.toml
cf usr/doc                doc

cf ~/sync/alan/diary/concards-data .local/share/concards
cf ~/sync/alan/diary/ttrack        .local/share/ttrack

# Ripgrep config can't recognize environment variables in its configuration.
# Putting the config here is my best solution.
cat << EOF > $HOME/.rgconfig
--no-heading
--no-follow
--hidden
--ignore-file=${HOME}/.dot/usr/search-ignore
EOF

systemctl daemon-reload --user

fi
