#!/usr/bin/zsh
if zmodload zsh/parameter 2>/dev/null && (( ${+options} )); then
  __fzf_key_bindings_options="options=(${(j: :)${(kv)options[@]}})"
else
  () {
    __fzf_key_bindings_options="setopt"
    local __fzf_opt
    for __fzf_opt in "${(@)${(@f)$(set -o)}%% *}"; do
      if [[ -o "$__fzf_opt" ]]; then
        __fzf_key_bindings_options+=" -o $__fzf_opt"
      else
        __fzf_key_bindings_options+=" +o $__fzf_opt"
      fi
    done
  }
fi

emulate zsh -o no_aliases

eval $__fzf_key_bindings_options
unset __fzf_key_bindings_options

[[ -o interactive ]] || return 0

# backspace stops at some extra characters
backward-kill-dir() {
    local WORDCHARS=${WORDCHARS/\//|}
    zle backward-kill-word
    zle -f kill
}

zshbind '^[^?' backward-kill-dir

# clean way to do zsh binding stuff
zshbind() {
    local func_name=$(echo "${@:2}" | tr ' ' '_')
    eval "$func_name"'() { '"${*:2}"' }'
    zle     -N   "$func_name"
    bindkey "$1" "$func_name"
}

kbf_command() {
    LBUFFER="$LBUFFER"$("$@")
    local ret=$?
    zle reset-prompt
    # next comment can be used to accept the line
    # [[ -n "$BUFFER" ]] && zle accept-line
    return $ret
}

# echo modes
zshbind '^ '  kbf_command fzf_modes
zshbind '^t'  kbf_command fzf_modes files
zshbind '^r'  kbf_command fzf_modes history
zshbind '\ec' kbf_command fzf_modes cd
