#!/bin/sh
sway 2>&1 | systemd-cat -t sway -p warning

# had this before for river:
# env XDG_SESSION_DESKTOP=sway XDG_CURRENT_DESKTOP=sway dbus-run-session /usr/bin/river -log-level error 2>&1 | systemd-cat -t river -p err
