hook global InsertChar k %{ try %{
      exec -draft hH <a-k>jk<ret> d
        exec <esc>
}}

set-option -add global ui_options ncurses_enable_mouse=off

map global user y '<a-|>xclip -selection clipboard<ret>'
map global user p '<|>xclip -selection clipboard -o<ret>'
map global user f '<|>tr "\n" " " | fold -s | awk "{\$1=\$1};1"<ret>'

eval %sh{kak-lsp --kakoune -s $kak_session}
hook global WinSetOption filetype=(rust|python|go|javascript|typescript|c|cpp) %{
    lsp-enable-window
}
