hook global InsertChar k %{ try %{
      exec -draft hH <a-k>jk<ret> d
        exec <esc>
}}

# Hacky way to disable the startup message on the scratch screen.
set-option global startup_info_version 99999999

# No picture of clippy.
set-option global ui_options ncurses_assistant=none

# Disable mouse support.
set-option -add global ui_options ncurses_enable_mouse=off

# Remove the scratch buffer message.
hook global BufCreate \*scratch\* %{
    execute-keys Ged <esc>
}

eval %sh{kak-lsp --kakoune -s $kak_session}
hook global WinSetOption filetype=(rust|python|go|javascript|typescript|c|cpp) %{
    lsp-enable-window
}

# Source files that contain commands.
source "%val{config}/fzf-mode.kak"
source "%val{config}/text-mode.kak"

# --- USER BINDINGS ---
# Clipboard management.
map global user y '<a-|>cclip<ret>'
map global user p '<|>pclip<ret>'

map global user g ': fzf-grep<ret>'

map -docstring 'enter fzf-mode' global user f ': fzf-mode<ret>'
map -docstring 'enter text-mode' global user t ': text-mode<ret>'
