#!/bin/bash
# assumes ufw and mcrcon are installed: https://github.com/Tiiffi/mcrcon.git

if [ "${EUID:-$(id -u)}" -ne 0 ]; then
    echo "Rerun this script as root! Exiting with non-zero error code."
    exit 1
fi

# after this script, make sure you download the minecraft installer:
# fabric   download: https://fabricmc.net/use/server/
# official download: https://www.minecraft.net/en-us/download/server

# user group mode destination
install_stdin() {
    local stdin=$(cat)
    local file=$(mktemp)
    cat > "$file" <<< "$stdin"
    install -o "$1" -g "$2" -m "$3" "$file" "$4"
    rm "$file"
}

ufw allow 25565 # allow minecraft port
ufw deny 25575  # deny rcon port to internet
useradd -Md /srv/minecraft minecraft
install -o minecraft -g minecraft -m 0700 -d /srv/minecraft

# create symbolic link if it doesn't exist
[ ! -L /srv/minecraft/minecraft_server.jar ] && (ln -fs /usr/bin/false /srv/minecraft/minecraft_server.jar)

install_stdin minecraft minecraft 0600 /srv/minecraft/eula.txt << EOF
eula=true
EOF

install_stdin minecraft minecraft 0600 /srv/minecraft/server.properties << EOF
allow-flight=false
allow-nether=true
broadcast-console-to-ops=true
broadcast-rcon-to-ops=true
difficulty=hard
enable-command-block=true
enable-jmx-monitoring=false
enable-query=false
enable-rcon=true
enable-status=true
enforce-secure-profile=true
enforce-whitelist=false
entity-broadcast-range-percentage=100
force-gamemode=true
function-permission-level=2
gamemode=survival
generate-structures=true
generator-settings={}
hardcore=false
hide-online-players=false
level-name=world
level-seed=
level-type=minecraft\:normal
max-chained-neighbor-updates=1000000
max-players=20
max-tick-time=-1
max-world-size=29999984
motd=\u00A7fMorgcraft\! \u00A74\u00A7omon-fri \u00A78\u00A7o19\:00-20\:30 us/mt\n\u00A7f......................... \u00A74\u00A7osat-sun \u00A78\u00A7o18\:00-21\:30 us/mt
network-compression-threshold=256
online-mode=true
op-permission-level=4
player-idle-timeout=0
prevent-proxy-connections=false
previews-chat=false
pvp=true
query.port=25565
rate-limit=0
rcon.password=pass
rcon.port=25575
require-resource-pack=false
resource-pack=
resource-pack-prompt=
resource-pack-sha1=
server-ip=
server-port=25565
simulation-distance=10
spawn-animals=true
spawn-monsters=true
spawn-npcs=true
spawn-protection=0
sync-chunk-writes=true
text-filtering-config=
use-native-transport=true
view-distance=10
white-list=false
EOF

echo '[]' | install_stdin minecraft minecraft 0600 /srv/minecraft/whitelist.json

awk '!/^\s*#/' << EOF | install_stdin minecraft minecraft 0600 /srv/minecraft/ops.json
[
  { "uuid": "de0f3b94-e2f5-4d79-8df8-fe7567ce7ecc", "name": "WolfFang181",    "level": 1, "bypassesPlayerLimit": true },
  { "uuid": "22536222-f7fd-455c-b3bf-6056eba7be5e", "name": "alanxoc3",       "level": 1, "bypassesPlayerLimit": true },
  { "uuid": "ecb96fe7-3c30-43cc-9c7d-e05f66814143", "name": "WadloTheWizard", "level": 1, "bypassesPlayerLimit": true },
  { "uuid": "7d0bbea7-7c5e-4fb3-91bb-9b9564b261b7", "name": "GreatCadet",     "level": 1, "bypassesPlayerLimit": true }
]
EOF

install_stdin root root 0500 /usr/local/bin/update_install_to_server << EOF
#!/bin/bash
curl -o /usr/local/bin/install_to_server https://raw.githubusercontent.com/alanxoc3/dotfiles/main/install_scripts/minecraft/install_to_server 2>/dev/null && chmod 700 /usr/local/bin/install_to_server
EOF

install_stdin root root 0644 /etc/systemd/system/minecraft-setup.service << EOF
[Unit]
After=local-fs.target network.target multi-user.target srv-minecraft.mount

[Service]
Type=oneshot
RemainAfterExit=yes
ExecStartPre=/usr/local/bin/update_install_to_server
ExecStart=/usr/local/bin/install_to_server

[Install]
WantedBy=network.target
EOF

JAVA_MAX_MEMORY=$(free -m | grep -E '^Mem:' | awk '{print int($2*.8)}')
install_stdin root root 0644 /etc/systemd/system/minecraft.service << EOF
[Unit]
After=local-fs.target network.target multi-user.target srv-minecraft.mount minecraft-setup.service

[Service]
User=minecraft
Group=minecraft
WorkingDirectory=/srv/minecraft
ExecStart=/usr/bin/java -Xms512M -Xmx${JAVA_MAX_MEMORY}M -jar minecraft_server.jar nogui

[Install]
WantedBy=network.target
EOF

install_stdin root root 0555 /usr/local/bin/mccmd << EOF
#!/bin/bash
mcrcon -p pass "\$@"
EOF

install_stdin root root 0500 /usr/local/bin/prep-for-shutdown << EOF
#!/bin/bash
BACKUP_COUNT=5

mccmd 'say ----------------------------'
mccmd 'say JOIN MORGCRAFT AGAIN TOMORROW!'
mccmd 'say ----------------------------'
mccmd 'say MON-FRI 19:00-20:30 US/MT'
mccmd 'say SAT-SUN 18:00-21:30 US/MT'
mccmd 'say ----------------------------'
mccmd 'say Server will shutdown in 60 seconds...'

for i in {50..30..10}; do
    sleep 10s
    mccmd "say \$i"
done

for i in {25..10..5}; do
    sleep 5s
    mccmd "say \$i"
done

for i in {9..1}; do
    sleep 1s
    mccmd "say \$i"
done

sleep 1s

mccmd 'say Saving and shutting down server...'
mccmd save-off
mccmd save-all

mkdir -p /srv/minecraft/backup
sleep 1s
sync

tar -czf /srv/minecraft/backup/"\$(date +%Y_%m_%d_%H.%M.%S).tar.gz" /srv/minecraft/world --totals
for f in \$(find /srv/minecraft/backup -mindepth 1 | sort -rV | awk "NR > \$BACKUP_COUNT"); do rm \$f; done
sync

mccmd save-on # in case command was run manually
mccmd 'say Goodbye!'
EOF

install_stdin root root 0500 /usr/local/bin/remove_extra_spaces << EOF
#!/usr/bin/python3
import re
import sys
print(re.sub("\s+", " ", sys.stdin.read()).strip())
EOF

install_stdin root root 0500 /usr/local/bin/mcqotd << EOF
#!/bin/bash
while sleep 5m; do
  mccmd "say THE KING DECREES: $(fortune -n 80 -s | remove_extra_spaces)"
done
EOF

install_stdin root root 0644 /etc/systemd/system/minecraft-qotd.service << EOF
[Unit]
After=minecraft.service

[Service]
WorkingDirectory=/srv/minecraft
ExecStart=/usr/local/bin/mcqotd

[Install]
WantedBy=network.target
EOF

systemctl daemon-reload
systemctl enable minecraft-setup.service minecraft.service minecraft-qotd.service
