#!/bin/bash -x
# This script installs the systemd files on a server.

pushd /etc/systemd/system/

cat << EOF | sudo tee minecraft-server-decree.service > /dev/null
[Unit]
Description=Server decree timer.

[Service]
ExecStart=$HOME/.dotfiles/bin/minecraft_server_decree
User=root
Group=root

[Install]
WantedBy=multi-user.target
EOF

cat << EOF | sudo tee minecraft-server-decree.timer > /dev/null
[Unit]
Description=Server decree for minecraft.

[Timer]
OnCalendar=*:0/30
AccuracySec=1m
Persistent=true

[Install]
WantedBy=timers.target
EOF

# Reload all the files we just added.
sudo systemctl daemon-reload

# Enable the services.
sudo systemctl enable minecraft-server-decree.timer

# And start them.
sudo systemctl restart minecraft-server-decree.timer
