#!/bin/bash
if [ "${EUID:-$(id -u)}" -ne 0 ]; then
    echo "Rerun this script as root! Exiting with non-zero error code."
    exit 1
fi

curl -o /usr/local/bin/linode-auto-minecraft https://raw.githubusercontent.com/alanxoc3/dotfiles/main/install_scripts/minecraft/linode-auto-minecraft 2>/dev/null && chmod 700 /usr/local/bin/linode-auto-minecraft

install_stdin() {
    local stdin=$(cat)
    local file=$(mktemp)
    cat > "$file" <<< "$stdin"
    install -o "$1" -g "$2" -m "$3" "$file" "$4"
    rm "$file"
}

install_stdin root root 0555 /usr/local/bin/mcsh << EOF
#!/bin/bash
ssh -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no -i /etc/minecraft/id_rsa mc.xoc3.io "$*"
exit $?
EOF

install_stdin root root 0555 /usr/local/bin/mcdestroywhenempty << EOF
#!/bin/bash
if [ timeout 30s mcsh mccmd list | sed -E 's/^There are ([0-9]+) .*/\1/g' -eq 0 ]; then
  mcdestroy
fi
EOF

install_stdin root root 0555 /usr/local/bin/mcdestroy << EOF
#!/bin/bash
mcsh prep-for-shutdown
linode-auto-minecraft destroy
EOF

install_stdin root root 0644 /etc/systemd/system/minecraft-build.service << EOF
[Service]
Type=oneshot
ExecStart=/usr/local/bin/linode-auto-minecraft build
EnvironmentFile=/etc/minecraft/setup.env
EOF

install_stdin root root 0644 /etc/systemd/system/minecraft-destroy.service << EOF
[Service]
Type=oneshot
ExecStart=/usr/local/bin/mcdestroywhenempty
EnvironmentFile=/etc/minecraft/setup.env
EOF

install_stdin root root 0644 /etc/systemd/system/minecraft-destroy.timer << EOF
[Timer]
OnBootSec=10min
OnUnitActiveSec=10min

[Install]
WantedBy=network.target
EOF

systemctl daemon-reload
systemctl enable minecraft-destroy.timer
systemctl start minecraft-destroy.timer
