#!/bin/bash
# Alan's arch install script for the user.
# This must be run after the root install, as the non-root user.

echo "Downloading dotfiles..."
git clone https://github.com/alanxoc3/dotfiles.git ~/.dot

echo "Setting up local git user..."
pushd ~/.dot
printf 'Name: ' ; read $NAME
printf 'Email: '; read $EMAIL
echo "[user]
   name = $NAME
   email = $EMAIL" > local_gitconfig

./setup.sh
popd

echo "Installing vim plug..."
sh -c 'curl -fLo "${XDG_DATA_HOME:-$HOME/.local/share}"/nvim/site/autoload/plug.vim --create-dirs https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim'

echo "Configuring tmux..."
git clone https://github.com/tmux-plugins/tpm ~/.tmux/plugins/tpm

echo "Making a 'repos' dir..."
mkdir repos
