#!/bin/bash
# A script that prepends your commit message with your case number.

COMMIT_MSG_FILE=$1
COMMIT_SOURCE=$2
SHA1=$3

nl='
'
case_regex="^([a-zA-Z]+-[0-9]+)"
gh_regex="^([0-9]+)"
text=$(git branch --show-current)
if [[ $text =~ $case_regex ]]; then
   name=$(echo "${BASH_REMATCH[1]}" | tr [a-z] [A-Z])
   sed -i.old '1s;^;['"$name"'] '"\\$nl"';' $COMMIT_MSG_FILE
elif [[ $text =~ $gh_regex ]]; then
   name="GH-${BASH_REMATCH[1]}"
   sed -i.old '1s;^;['"$name"'] '"\\$nl"';' $COMMIT_MSG_FILE
fi

# Append the diff to the comments
echo "# REPO LOCATION: $(git rev-parse --show-toplevel)" >> $COMMIT_MSG_FILE; echo
echo '# DIFFERENCES TO BE COMMITTED:' >> $COMMIT_MSG_FILE
git diff --staged | awk '{print "# " $0;}' >> $COMMIT_MSG_FILE
