snippet_support = false
verbosity = 2

[server]
timeout = 1800

[language.java]
filetypes = ["java"]
roots = ["pom.xml"]
command = "/Users/alanmorgan/repos/jdtls/bin/jdtls"
args = ["-data", "/Users/alanmorgan/cw"]

[language.gdscript]
filetypes = ["gd", "gdscript"]
roots = [".import", "project.godot"]
command = "nc"
args = ["localhost", "6008"]

[language.bash]
filetypes = ["sh"]
roots = [".git", ".hg"]
command = "bash-language-server"
args = ["start"]

[language.c_cpp]
filetypes = ["c", "cpp"]
roots = ["compile_commands.json", ".clangd", ".git", ".hg"]
command = "clangd"

[language.crystal]
filetypes = ["crystal"]
roots = ["shard.yml"]
command = "scry"

[language.css]
filetypes = ["css"]
roots = ["package.json", ".git", ".hg"]
command = "css-languageserver"
args = ["--stdio"]

[language.less]
filetypes = ["less"]
roots = ["package.json", ".git", ".hg"]
command = "css-languageserver"
args = ["--stdio"]

[language.scss]
filetypes = ["scss"]
roots = ["package.json", ".git", ".hg"]
command = "css-languageserver"
args = ["--stdio"]

[language.d]
filetypes = ["d", "di"]
roots = [".git", "dub.sdl", "dub.json"]
command = "dls"

[language.dart]
filetypes = ["dart"]
roots = ["pubspec.yaml", ".git", ".hg"]
command = "sh"
args = ["-c", "dart $(dirname $(command -v dart))/snapshots/analysis_server.dart.snapshot --lsp"]

[language.elixir]
filetypes = ["elixir"]
roots = ["mix.exs"]
command = "elixir-ls"
settings_section = "elixirLS"
[language.elixir.settings.elixirLS]

[language.elm]
filetypes = ["elm"]
roots = ["elm.json"]
command = "elm-language-server"
args = ["--stdio"]
settings_section = "elmLS"
[language.elm.settings.elmLS]
runtime = "node"
elmPath = "elm"
elmFormatPath = "elm-format"
elmTestPath = "elm-test"

[language.erlang]
filetypes = ["erlang"]
roots = ["rebar.config", "erlang.mk", ".git", ".hg"]
command = "erlang_ls"

[language.go]
filetypes = ["go"]
roots = ["Gopkg.toml", "go.mod", ".git", ".hg"]
command = "gopls"
settings_section = "gopls"
[language.go.settings.gopls]

[language.haskell]
filetypes = ["haskell"]
roots = ["Setup.hs", "stack.yaml", "*.cabal"]
command = "haskell-language-server-wrapper"
args = ["--lsp"]
settings_section = "_"
[language.haskell.settings._]

[language.html]
filetypes = ["html"]
roots = ["package.json"]
command = "html-languageserver"
args = ["--stdio"]


[language.javascript]
filetypes = ["javascript"]
roots = [".flowconfig"]
command = "flow"
args = ["lsp"]

[language.json]
filetypes = ["json"]
roots = ["package.json"]
command = "json-languageserver"
args = ["--stdio"]

[language.julia]
filetypes = ["julia"]
roots = ["Project.toml", ".git", ".hg"]
command = "julia"
args = [
    "--startup-file=no",
    "--history-file=no",
    "-e",
    """
        using LanguageServer;
        using Pkg;
        import StaticLint;
        import SymbolServer;
        import REPL;
        env_path = dirname(Pkg.Types.Context().env.project_file);
        server = LanguageServer.LanguageServerInstance(stdin, stdout, env_path, "");
        server.runlinter = true;
        run(server);
    """,
]
[language.julia.settings]

[language.latex]
filetypes = ["latex"]
roots = [".git", ".hg"]
command = "texlab"
settings_section = "texlab"
[language.latex.settings.texlab]
forwardSearch.executable = "zathura"
forwardSearch.args = [
    "%p",
    "--synctex-forward",
    "%l:1:%f",
    "--synctex-editor-command",
    """
        sh -c '
            echo "
                evaluate-commands -client $kak_client %{
                    evaluate-commands -try-client %opt{jumpclient} %{
                        edit -- %{input} %{line}
                    }
                }
            " | kak -p $kak_session
        '
    """,
]

[language.lua]
filetypes = ["lua"]
roots = [".git", ".hg"]
command = "lua-language-server"
[language.lua.settings.Lua]

[language.nim]
filetypes = ["nim"]
roots = ["*.nimble", ".git", ".hg"]
command = "nimlsp"

[language.nix]
filetypes = ["nix"]
roots = ["flake.nix", "shell.nix", ".git", ".hg"]
command = "rnix-lsp"

[language.ocaml]
filetypes = ["ocaml"]
roots = ["Makefile", "opam", "*.opam", "dune"]
command = "ocamllsp"

[language.php]
filetypes = ["php"]
roots = [".htaccess", "composer.json"]
command = "intelephense"
args = ["--stdio"]
settings_section = "intelephense"
[language.php.settings]
intelephense.storagePath = "/tmp/intelephense"

[language.python]
filetypes = ["python"]
roots = ["uv.lock", "reqs.txt", "requirements.txt", "setup.py", ".git", ".hg", "pyproject.toml"]
command = "venv_pylsp"
settings_section = "_"
args = ["-v"] # verbose

[language.python.settings._]
# this helped: https://jdhao.github.io/2023/07/22/neovim-pylsp-setup/
pylsp.plugins.pylint.enabled = true
pylsp.plugins.pylint.executable = "pylint"
pylsp.plugins.pylint.args = [ "-v" ]
pylsp.plugins.mccabe.threshold = 30 # cyclomatic threshold. https://github.com/python-lsp/python-lsp-server/blob/cc6d398befddb0c9b0f0a52affade3ca4fbfded4/CONFIGURATION.md
pylsp.plugins.black.enabled         = true
pylsp.plugins.pylsp_mypy.enabled    = true
pylsp.plugins.jedi_completion.fuzzy = true
pylsp.plugins.pyls_isort.enabled    = true
pylsp.plugins.autopep8.enabled      = false
pylsp.plugins.yapf.enabled          = false
pylsp.plugins.pyflakes.enabled      = false
pylsp.plugins.pycodestyle.enabled   = false
# pylsp.pylint.args = [ "-f", "json" ]

[language.r]
filetypes = ["r"]
roots = ["DESCRIPTION", ".git", ".hg"]
command = "R"
args = ["--slave", "-e", "languageserver::run()"]

[language.racket]
filetypes = ["racket"]
roots = ["info.rkt"]
command = "racket"
args = ["-l", "racket-langserver"]

[language.reason]
filetypes = ["reason"]
roots = ["package.json", "Makefile", ".git", ".hg"]
command = "ocamllsp"

[language.ruby]
filetypes = ["ruby"]
roots = ["Gemfile"]
command = "solargraph"
args = ["stdio"]
[language.ruby.settings]


[language.rust]
filetypes = ["rust"]
roots = ["Cargo.toml"]
command = "sh"
args = [
    "-c",
    """
        if path=$(rustup which rust-analyzer 2>/dev/null); then
            "$path"
        else
            rust-analyzer
        fi
    """,
]
settings_section = "rust-analyzer"
[language.rust.settings.rust-analyzer]
procMacro.enable = true
hoverActions.enable = false
cargo.loadOutDirsFromCheck = false

[language.terraform]
filetypes = ["terraform"]
roots = ["*.tf"]
command = "terraform-ls"
args = ["serve"]
[language.terraform.settings.terraform-ls]

[language.typescript]
filetypes = ["typescript"]
roots = ["package.json", "tsconfig.json", ".git", ".hg", ".ts"]
command = "bunx"
args = ["typescript-language-server", "--stdio"]

[language.typescript.settings]
plugins = [{name = "@vue/typescript-plugin", location = "/home/alan/job/fidalgo/node_modules/@vue/language-server", languages = ["vue"]}]

[language.vue]
filetypes = ["vue"]
roots = ["package.json"]
command = "bunx"
args = ["vue-language-server", "--stdio"]
settings_section = "_"

[language.vue.settings._]
vue = { hybridMode = false }
typescript = { tsdk = "/home/alan/job/fidalgo/node_modules/typescript/lib" }

[language.yaml]
filetypes = ["yaml"]
roots = [".git", ".hg"]
command = "yaml-language-server"
args = ["--stdio"]

[language.yaml.settings.yaml]
schemaStore.enable = true

[language.zig]
filetypes = ["zig"]
roots = ["build.zig"]
command = "zls"

[semantic_tokens]
faces = [
    {face="documentation", token="comment", modifiers=["documentation"]},
    {face="comment", token="comment"},
    {face="function", token="function"},
    {face="keyword", token="keyword"},
    {face="module", token="namespace"},
    {face="operator", token="operator"},
    {face="string", token="string"},
    {face="type", token="type"},
    {face="default+d", token="variable", modifiers=["readonly"]},
    {face="default+d", token="variable", modifiers=["constant"]},
    {face="variable", token="variable"},
]
